export const GET_ALL_JOB_REQUEST = "GET_ALL_JOB_REQUEST";
export const GET_ALL_JOB_SUCCESS = "GET_ALL_JOB_SUCCESS";
export const GET_ALL_JOB_FAIL = "GET_ALL_JOB_FAIL";

export const GET_SINGLE_JOB_REQUEST = "GET_SINGLE_JOB_REQUEST";
export const GET_SINGLE_JOB_SUCCESS = "GET_SINGLE_JOB_SUCCESS";
export const GET_SINGLE_JOB_FAIL = "GET_SINGLE_JOB_FAIL";

export const APPLY_JOB_REQUEST = "APPLY_JOB_REQUEST";
export const APPLY_JOB_SUCCESS = "APPLY_JOB_SUCCESS";
export const APPLY_JOB_FAIL = "APPLY_JOB_FAIL";
